---
- name: Automate app to install on M1 MacOS
  hosts: localhost
  gather_facts: false
  # become: true

### manual installation is prefered as of now
#--> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#--> echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/[username]/.zprofile
#--> eval "$(/opt/homebrew/bin/brew shellenv)"
  tasks:
    - name: Install applications using Homebrew Cask for GUI apps
      # become: yes
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - sublime-text
        - visual-studio-code
        - docker
        - iterm2
        - slack
        - google-chrome

    # - name: Check if Visual Studio Code is installed
    #   shell: brew list --cask | grep visual-studio-code
    #   register: vscode_check
    #   changed_when: false
    #   ignore_errors: true

    # - name: Install Visual Studio Code
    #   shell: brew install --cask visual-studio-code
    #   when: vscode_check.rc != 0


    # - name: Install iTerm2
    #   homebrew_cask:
    #     name: iterm2
    #     state: present

    - name: Install Oh My Zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: $HOME/.oh-my-zsh

    - name: clone these repo's for iTerm2
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
      loop:
        - { repo: 'https://github.com/romkatv/powerlevel10k.git', dest: '$HOME/.oh-my-zsh/custom/themes/powerlevel10k' }
        - { repo: 'https://github.com/zsh-users/zsh-autosuggestions', dest: '$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions' }
        - { repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git', dest: '$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting' }    
        - { repo: 'https://github.com/asdf-vm/asdf.git', dest: '~/.asdf' }

    # - name: Clone asdf repository
    #   shell: git clone https://github.com/asdf-vm/asdf.git ~/.asdf
    #   args:
    #     creates: $HOME/.asdf

    - name: Configure ZSH_THEME in .zshrc
      lineinfile:
        path: ~/.zshrc
        regexp: '^ZSH_THEME='
        line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'

    - name: Configure plugins in .zshrc
      lineinfile:
        path: ~/.zshrc
        regexp: '^plugins='
        line: 'plugins=(git zsh-autosuggestions zsh-syntax-highlighting web-search asdf)'

    - name: Update Homebrew
      command: brew update

    # - name: Install Docker desktop
    #   homebrew_cask:
    #     name: docker
    #     state: present

## alternative way to install python-yq
    # - name: Install python-yq using pip
    #   pip:
    #     name: yq
    #     state: present

    - name: Install apps/packages iteratively wget, pyenv, jq ,,,
      homebrew:
        name: "{{ item }}"
        state: present
      with_items:
        - wget
        - pyenv
        - pyenv-virtualenv #to support pyarrow
        - jq
        - warrensbox/tap/tfswitch
        - libyaml
        - pyenv-virtualenvwrapper
        - awscli
        # - expect # to handle prompts
